# The MIT License
#
# Copyright 2020 Noor Dawod. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

name: "localison"
description: "Provides localization support to a Flutter app using JSON files."
version: "0.0.3"
homepage: "https://github.com/ndawod"

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: "flutter"

  sprintf: "^4.0.2"

dev_dependencies:
  flutter_test:
    sdk: "flutter"

  pedantic: "1.9.0"

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: "com.example.localison"
        pluginClass: "LocalisonPlugin"
      ios:
        pluginClass: "LocalisonPlugin"
